---START---
-- sanity check of system catalog
SELECT attrelid, attname, attgenerated FROM pg_attribute WHERE attgenerated NOT IN ('', 's');
---END---
---START---
CREATE TABLE gtest0 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (55) STORED);
---END---
---START---
CREATE TABLE gtest1 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
SELECT table_name, column_name, column_default, is_nullable, is_generated, generation_expression FROM information_schema.columns WHERE table_name LIKE 'gtest_' ORDER BY 1, 2;
---END---
---START---
SELECT table_name, column_name, dependent_column FROM information_schema.column_column_usage ORDER BY 1, 2, 3;
---END---
---START---
\d gtest1

-- duplicate generated
CREATE TABLE gtest_err_1 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED GENERATED ALWAYS AS (a * 3) STORED);
---END---
---START---
-- references to other generated columns, including self-references
CREATE TABLE gtest_err_2a (a int PRIMARY KEY, b int GENERATED ALWAYS AS (b * 2) STORED);
---END---
---START---
CREATE TABLE gtest_err_2b (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED, c int GENERATED ALWAYS AS (b * 3) STORED);
---END---
---START---
-- a whole-row var is a self-reference on steroids, so disallow that too
CREATE TABLE gtest_err_2c (a int PRIMARY KEY,
    b int GENERATED ALWAYS AS (num_nulls(gtest_err_2c)) STORED);
---END---
---START---
-- invalid reference
CREATE TABLE gtest_err_3 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (c * 2) STORED);
---END---
---START---
-- generation expression must be immutable
CREATE TABLE gtest_err_4 (a int PRIMARY KEY, b double precision GENERATED ALWAYS AS (random()) STORED);
---END---
---START---
-- cannot have default/identity and generated
CREATE TABLE gtest_err_5a (a int PRIMARY KEY, b int DEFAULT 5 GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
CREATE TABLE gtest_err_5b (a int PRIMARY KEY, b int GENERATED ALWAYS AS identity GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
-- reference to system column not allowed in generated column
-- (except tableoid, which we test below)
CREATE TABLE gtest_err_6a (a int PRIMARY KEY, b bool GENERATED ALWAYS AS (xmin <> 37) STORED);
---END---
---START---
-- various prohibited constructs
CREATE TABLE gtest_err_7a (a int PRIMARY KEY, b int GENERATED ALWAYS AS (avg(a)) STORED);
---END---
---START---
CREATE TABLE gtest_err_7b (a int PRIMARY KEY, b int GENERATED ALWAYS AS (row_number() OVER (ORDER BY a)) STORED);
---END---
---START---
CREATE TABLE gtest_err_7c (a int PRIMARY KEY, b int GENERATED ALWAYS AS ((SELECT a)) STORED);
---END---
---START---
CREATE TABLE gtest_err_7d (a int PRIMARY KEY, b int GENERATED ALWAYS AS (generate_series(1, a)) STORED);
---END---
---START---
-- GENERATED BY DEFAULT not allowed
CREATE TABLE gtest_err_8 (a int PRIMARY KEY, b int GENERATED BY DEFAULT AS (a * 2) STORED);
---END---
---START---
INSERT INTO gtest1 VALUES (1);
---END---
---START---
INSERT INTO gtest1 VALUES (2, DEFAULT);
---END---
---START---
-- ok
INSERT INTO gtest1 VALUES (3, 33);
---END---
---START---
-- error
INSERT INTO gtest1 VALUES (3, 33), (4, 44);
---END---
---START---
-- error
INSERT INTO gtest1 VALUES (3, DEFAULT), (4, 44);
---END---
---START---
-- error
INSERT INTO gtest1 VALUES (3, 33), (4, DEFAULT);
---END---
---START---
-- error
INSERT INTO gtest1 VALUES (3, DEFAULT), (4, DEFAULT);
---END---
---START---
-- ok

SELECT * FROM gtest1 ORDER BY a;
---END---
---START---
DELETE FROM gtest1 WHERE a >= 3;
---END---
---START---
UPDATE gtest1 SET b = DEFAULT WHERE a = 1;
---END---
---START---
UPDATE gtest1 SET b = 11 WHERE a = 1;
---END---
---START---
-- error

SELECT * FROM gtest1 ORDER BY a;
---END---
---START---
SELECT a, b, b * 2 AS b2 FROM gtest1 ORDER BY a;
---END---
---START---
SELECT a, b FROM gtest1 WHERE b = 4 ORDER BY a;
---END---
---START---
-- test that overflow error happens on write
INSERT INTO gtest1 VALUES (2000000000);
---END---
---START---
SELECT * FROM gtest1;
---END---
---START---
DELETE FROM gtest1 WHERE a = 2000000000;
---END---
---START---
CREATE TABLE gtestx (gemini_pk serial PRIMARY KEY, x integer, y integer);
---END---
---START---
INSERT INTO gtestx VALUES (11, 1), (22, 2), (33, 3);
---END---
---START---
SELECT * FROM gtestx, gtest1 WHERE gtestx.y = gtest1.a;
---END---
---START---
DROP TABLE gtestx;
---END---
---START---
-- test UPDATE/DELETE quals
SELECT * FROM gtest1 ORDER BY a;
---END---
---START---
UPDATE gtest1 SET a = 3 WHERE b = 4;
---END---
---START---
SELECT * FROM gtest1 ORDER BY a;
---END---
---START---
DELETE FROM gtest1 WHERE b = 2;
---END---
---START---
SELECT * FROM gtest1 ORDER BY a;
---END---
---START---
-- test MERGE
CREATE TABLE gtestm (
  id int PRIMARY KEY,
  f1 int,
  f2 int,
  f3 int GENERATED ALWAYS AS (f1 * 2) STORED,
  f4 int GENERATED ALWAYS AS (f2 * 2) STORED
);
---END---
---START---
INSERT INTO gtestm VALUES (1, 5, 100);
---END---
---START---
MERGE INTO gtestm t USING (VALUES (1, 10), (2, 20)) v(id, f1) ON t.id = v.id
  WHEN MATCHED THEN UPDATE SET f1 = v.f1
  WHEN NOT MATCHED THEN INSERT VALUES (v.id, v.f1, 200);
---END---
---START---
SELECT * FROM gtestm ORDER BY id;
---END---
---START---
DROP TABLE gtestm;
---END---
---START---
-- views
CREATE VIEW gtest1v AS SELECT * FROM gtest1;
---END---
---START---
SELECT * FROM gtest1v;
---END---
---START---
INSERT INTO gtest1v VALUES (4, 8);
---END---
---START---
-- error
INSERT INTO gtest1v VALUES (5, DEFAULT);
---END---
---START---
-- ok
INSERT INTO gtest1v VALUES (6, 66), (7, 77);
---END---
---START---
-- error
INSERT INTO gtest1v VALUES (6, DEFAULT), (7, 77);
---END---
---START---
-- error
INSERT INTO gtest1v VALUES (6, 66), (7, DEFAULT);
---END---
---START---
-- error
INSERT INTO gtest1v VALUES (6, DEFAULT), (7, DEFAULT);
---END---
---START---
-- ok

ALTER VIEW gtest1v ALTER COLUMN b SET DEFAULT 100;
---END---
---START---
INSERT INTO gtest1v VALUES (8, DEFAULT);
---END---
---START---
-- error
INSERT INTO gtest1v VALUES (8, DEFAULT), (9, DEFAULT);
---END---
---START---
-- error

SELECT * FROM gtest1v;
---END---
---START---
DELETE FROM gtest1v WHERE a >= 5;
---END---
---START---
DROP VIEW gtest1v;
---END---
---START---
-- CTEs
WITH foo AS (SELECT * FROM gtest1) SELECT * FROM foo;
---END---
---START---
CREATE TABLE gtest1_1 (gemini_pk serial PRIMARY KEY) INHERITS (gtest1);
---END---
---START---
SELECT * FROM gtest1_1;
---END---
---START---
\d gtest1_1
INSERT INTO gtest1_1 VALUES (4);
---END---
---START---
SELECT * FROM gtest1_1;
---END---
---START---
SELECT * FROM gtest1;
---END---
---START---
CREATE TABLE gtest_normal (gemini_pk serial PRIMARY KEY, a integer, b integer);
---END---
---START---
CREATE TABLE gtest_normal_child (gemini_pk serial PRIMARY KEY, a integer, b integer GENERATED ALWAYS AS (a * 2) STORED) INHERITS (gtest_normal);
---END---
---START---
CREATE TABLE gtest_normal_child (gemini_pk serial PRIMARY KEY, a integer, b integer GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
ALTER TABLE gtest_normal_child INHERIT gtest_normal;
---END---
---START---
-- error
DROP TABLE gtest_normal, gtest_normal_child;
---END---
---START---
CREATE TABLE gtestx (gemini_pk serial PRIMARY KEY, x integer, b integer DEFAULT 10) INHERITS (gtest1);
---END---
---START---
CREATE TABLE gtestx (gemini_pk serial PRIMARY KEY, x integer, b integer GENERATED ALWAYS AS IDENTITY) INHERITS (gtest1);
---END---
---START---
CREATE TABLE gtestx (gemini_pk serial PRIMARY KEY, x integer, b integer GENERATED ALWAYS AS (a * 22) STORED) INHERITS (gtest1);
---END---
---START---
-- ok, overrides parent
\d+ gtestx

CREATE TABLE gtestxx_1 (gemini_pk serial PRIMARY KEY, a int NOT NULL, b int);
---END---
---START---
ALTER TABLE gtestxx_1 INHERIT gtest1;
---END---
---START---
CREATE TABLE gtestxx_3 (gemini_pk serial PRIMARY KEY, a integer NOT NULL, b integer GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
ALTER TABLE gtestxx_3 INHERIT gtest1;
---END---
---START---
CREATE TABLE gtestxx_4 (gemini_pk serial PRIMARY KEY, b integer GENERATED ALWAYS AS (a * 2) STORED, a integer NOT NULL);
---END---
---START---
ALTER TABLE gtestxx_4 INHERIT gtest1;
---END---
---START---
CREATE TABLE gtesty (gemini_pk serial PRIMARY KEY, x integer, b integer DEFAULT 55);
---END---
---START---
CREATE TABLE gtest1_y (gemini_pk serial PRIMARY KEY) INHERITS (gtest0, gtesty);
---END---
---START---
-- error
DROP TABLE gtesty;
---END---
---START---
CREATE TABLE gtesty (gemini_pk serial PRIMARY KEY, x integer, b integer);
---END---
---START---
CREATE TABLE gtest1_y (gemini_pk serial PRIMARY KEY) INHERITS (gtest1, gtesty);
---END---
---START---
-- error
DROP TABLE gtesty;
---END---
---START---
CREATE TABLE gtesty (gemini_pk serial PRIMARY KEY, x integer, b integer GENERATED ALWAYS AS (x * 22) STORED);
---END---
---START---
CREATE TABLE gtest1_y (gemini_pk serial PRIMARY KEY) INHERITS (gtest1, gtesty);
---END---
---START---
CREATE TABLE gtest1_y (gemini_pk serial PRIMARY KEY, b integer GENERATED ALWAYS AS (x + 1) STORED) INHERITS (gtest1, gtesty);
---END---
---START---
-- ok
\d gtest1_y

-- test correct handling of GENERATED column that's only in child
CREATE TABLE gtestp (gemini_pk serial PRIMARY KEY, f1 int);
---END---
---START---
CREATE TABLE gtestc (gemini_pk serial PRIMARY KEY, f2 integer GENERATED ALWAYS AS (f1 + 1) STORED) INHERITS (gtestp);
---END---
---START---
INSERT INTO gtestc values(42);
---END---
---START---
TABLE gtestc;
---END---
---START---
UPDATE gtestp SET f1 = f1 * 10;
---END---
---START---
TABLE gtestc;
---END---
---START---
DROP TABLE gtestp CASCADE;
---END---
---START---
CREATE TABLE gtest3 (gemini_pk serial PRIMARY KEY, a integer, b integer GENERATED ALWAYS AS (a * 3) STORED);
---END---
---START---
INSERT INTO gtest3 (a) VALUES (1), (2), (3), (NULL);
---END---
---START---
SELECT * FROM gtest3 ORDER BY a;
---END---
---START---
UPDATE gtest3 SET a = 22 WHERE a = 2;
---END---
---START---
SELECT * FROM gtest3 ORDER BY a;
---END---
---START---
CREATE TABLE gtest3a (gemini_pk serial PRIMARY KEY, a text, b text GENERATED ALWAYS AS ((a || '+') || a) STORED);
---END---
---START---
INSERT INTO gtest3a (a) VALUES ('a'), ('b'), ('c'), (NULL);
---END---
---START---
SELECT * FROM gtest3a ORDER BY a;
---END---
---START---
UPDATE gtest3a SET a = 'bb' WHERE a = 'b';
---END---
---START---
SELECT * FROM gtest3a ORDER BY a;
---END---
---START---
-- COPY
TRUNCATE gtest1;
---END---
---START---
INSERT INTO gtest1 (a) VALUES (1), (2);
---END---
---START---
COPY gtest1 TO stdout;

COPY gtest1 (a, b) TO stdout;

COPY gtest1 FROM stdin;
3
4
\.
---END---
---START---
COPY gtest1 (a, b) FROM stdin;

SELECT * FROM gtest1 ORDER BY a;

TRUNCATE gtest3;
INSERT INTO gtest3 (a) VALUES (1), (2);

COPY gtest3 TO stdout;

COPY gtest3 (a, b) TO stdout;

COPY gtest3 FROM stdin;
3
4
\.
---END---
---START---
COPY gtest3 (a, b) FROM stdin;
---END---
---START---
SELECT * FROM gtest3 ORDER BY a;
---END---
---START---
-- null values
CREATE TABLE gtest2 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (NULL) STORED);
---END---
---START---
INSERT INTO gtest2 VALUES (1);
---END---
---START---
SELECT * FROM gtest2;
---END---
---START---
CREATE TABLE gtest_varlena (gemini_pk serial PRIMARY KEY, a varchar, b varchar GENERATED ALWAYS AS (a) STORED);
---END---
---START---
INSERT INTO gtest_varlena (a) VALUES('01234567890123456789');
---END---
---START---
INSERT INTO gtest_varlena (a) VALUES(NULL);
---END---
---START---
SELECT * FROM gtest_varlena ORDER BY a;
---END---
---START---
DROP TABLE gtest_varlena;
---END---
---START---
-- composite types
CREATE TYPE double_int as (a int, b int);
---END---
---START---
CREATE TABLE gtest4 (gemini_pk serial PRIMARY KEY, a integer, b double_int GENERATED ALWAYS AS ((a * 2, a * 3)) STORED);
---END---
---START---
INSERT INTO gtest4 VALUES (1), (6);
---END---
---START---
SELECT * FROM gtest4;
---END---
---START---
DROP TABLE gtest4;
---END---
---START---
DROP TYPE double_int;
---END---
---START---
-- using tableoid is allowed
CREATE TABLE gtest_tableoid (
  a int PRIMARY KEY,
  b bool GENERATED ALWAYS AS (tableoid = 'gtest_tableoid'::regclass) STORED
);
---END---
---START---
INSERT INTO gtest_tableoid VALUES (1), (2);
---END---
---START---
ALTER TABLE gtest_tableoid ADD COLUMN
  c regclass GENERATED ALWAYS AS (tableoid) STORED;
---END---
---START---
SELECT * FROM gtest_tableoid;
---END---
---START---
-- drop column behavior
CREATE TABLE gtest10 (a int PRIMARY KEY, b int, c int GENERATED ALWAYS AS (b * 2) STORED);
---END---
---START---
ALTER TABLE gtest10 DROP COLUMN b;
---END---
---START---
-- fails
ALTER TABLE gtest10 DROP COLUMN b CASCADE;
---END---
---START---
-- drops c too

\d gtest10

CREATE TABLE gtest10a (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
ALTER TABLE gtest10a DROP COLUMN b;
---END---
---START---
INSERT INTO gtest10a (a) VALUES (1);
---END---
---START---
-- privileges
CREATE USER regress_user11;
---END---
---START---
CREATE TABLE gtest11s (a int PRIMARY KEY, b int, c int GENERATED ALWAYS AS (b * 2) STORED);
---END---
---START---
INSERT INTO gtest11s VALUES (1, 10), (2, 20);
---END---
---START---
GRANT SELECT (a, c) ON gtest11s TO regress_user11;
---END---
---START---
CREATE FUNCTION gf1(a int) RETURNS int AS $$ SELECT a * 3 $$ IMMUTABLE LANGUAGE SQL;
---END---
---START---
REVOKE ALL ON FUNCTION gf1(int) FROM PUBLIC;
---END---
---START---
CREATE TABLE gtest12s (a int PRIMARY KEY, b int, c int GENERATED ALWAYS AS (gf1(b)) STORED);
---END---
---START---
INSERT INTO gtest12s VALUES (1, 10), (2, 20);
---END---
---START---
GRANT SELECT (a, c) ON gtest12s TO regress_user11;
---END---
---START---
SET ROLE regress_user11;
---END---
---START---
SELECT a, b FROM gtest11s;
---END---
---START---
-- not allowed
SELECT a, c FROM gtest11s;
---END---
---START---
-- allowed
SELECT gf1(10);
---END---
---START---
-- not allowed
SELECT a, c FROM gtest12s;
---END---
---START---
-- allowed
RESET ROLE;
---END---
---START---
DROP FUNCTION gf1(int);
---END---
---START---
-- fail
DROP TABLE gtest11s, gtest12s;
---END---
---START---
DROP FUNCTION gf1(int);
---END---
---START---
DROP USER regress_user11;
---END---
---START---
-- check constraints
CREATE TABLE gtest20 (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED CHECK (b < 50));
---END---
---START---
INSERT INTO gtest20 (a) VALUES (10);
---END---
---START---
-- ok
INSERT INTO gtest20 (a) VALUES (30);
---END---
---START---
-- violates constraint

CREATE TABLE gtest20a (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
INSERT INTO gtest20a (a) VALUES (10);
---END---
---START---
INSERT INTO gtest20a (a) VALUES (30);
---END---
---START---
ALTER TABLE gtest20a ADD CHECK (b < 50);
---END---
---START---
-- fails on existing row

CREATE TABLE gtest20b (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
INSERT INTO gtest20b (a) VALUES (10);
---END---
---START---
INSERT INTO gtest20b (a) VALUES (30);
---END---
---START---
ALTER TABLE gtest20b ADD CONSTRAINT chk CHECK (b < 50) NOT VALID;
---END---
---START---
ALTER TABLE gtest20b VALIDATE CONSTRAINT chk;
---END---
---START---
-- fails on existing row

-- not-null constraints
CREATE TABLE gtest21a (a int PRIMARY KEY, b int GENERATED ALWAYS AS (nullif(a, 0)) STORED NOT NULL);
---END---
---START---
INSERT INTO gtest21a (a) VALUES (1);
---END---
---START---
-- ok
INSERT INTO gtest21a (a) VALUES (0);
---END---
---START---
-- violates constraint

CREATE TABLE gtest21b (a int PRIMARY KEY, b int GENERATED ALWAYS AS (nullif(a, 0)) STORED);
---END---
---START---
ALTER TABLE gtest21b ALTER COLUMN b SET NOT NULL;
---END---
---START---
INSERT INTO gtest21b (a) VALUES (1);
---END---
---START---
-- ok
INSERT INTO gtest21b (a) VALUES (0);
---END---
---START---
-- violates constraint
ALTER TABLE gtest21b ALTER COLUMN b DROP NOT NULL;
---END---
---START---
INSERT INTO gtest21b (a) VALUES (0);
---END---
---START---
-- ok now

-- index constraints
CREATE TABLE gtest22a (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a / 2) STORED UNIQUE);
---END---
---START---
INSERT INTO gtest22a VALUES (2);
---END---
---START---
INSERT INTO gtest22a VALUES (3);
---END---
---START---
INSERT INTO gtest22a VALUES (4);
---END---
---START---
CREATE TABLE gtest22b (a int, b int GENERATED ALWAYS AS (a / 2) STORED, PRIMARY KEY (a, b));
---END---
---START---
INSERT INTO gtest22b VALUES (2);
---END---
---START---
INSERT INTO gtest22b VALUES (2);
---END---
---START---
CREATE TABLE gtest22c (gemini_pk serial PRIMARY KEY, a integer, b integer GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
CREATE INDEX gtest22c_b_idx ON gtest22c (b);
---END---
---START---
CREATE INDEX gtest22c_expr_idx ON gtest22c ((b * 3));
---END---
---START---
CREATE INDEX gtest22c_pred_idx ON gtest22c (a) WHERE b > 0;
---END---
---START---
\d gtest22c

INSERT INTO gtest22c VALUES (1), (2), (3);
---END---
---START---
SET enable_seqscan TO off;
---END---
---START---
SET enable_bitmapscan TO off;
---END---
---START---
EXPLAIN (COSTS OFF) SELECT * FROM gtest22c WHERE b = 4;
---END---
---START---
SELECT * FROM gtest22c WHERE b = 4;
---END---
---START---
EXPLAIN (COSTS OFF) SELECT * FROM gtest22c WHERE b * 3 = 6;
---END---
---START---
SELECT * FROM gtest22c WHERE b * 3 = 6;
---END---
---START---
EXPLAIN (COSTS OFF) SELECT * FROM gtest22c WHERE a = 1 AND b > 0;
---END---
---START---
SELECT * FROM gtest22c WHERE a = 1 AND b > 0;
---END---
---START---
RESET enable_seqscan;
---END---
---START---
RESET enable_bitmapscan;
---END---
---START---
-- foreign keys
CREATE TABLE gtest23a (x int PRIMARY KEY, y int);
---END---
---START---
INSERT INTO gtest23a VALUES (1, 11), (2, 22), (3, 33);
---END---
---START---
CREATE TABLE gtest23x (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED REFERENCES gtest23a (x) ON UPDATE CASCADE);
---END---
---START---
-- error
CREATE TABLE gtest23x (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED REFERENCES gtest23a (x) ON DELETE SET NULL);
---END---
---START---
-- error

CREATE TABLE gtest23b (a int PRIMARY KEY, b int GENERATED ALWAYS AS (a * 2) STORED REFERENCES gtest23a (x));
---END---
---START---
\d gtest23b

INSERT INTO gtest23b VALUES (1);
---END---
---START---
-- ok
INSERT INTO gtest23b VALUES (5);
---END---
---START---
-- error

DROP TABLE gtest23b;
---END---
---START---
DROP TABLE gtest23a;
---END---
---START---
CREATE TABLE gtest23p (x int, y int GENERATED ALWAYS AS (x * 2) STORED, PRIMARY KEY (y));
---END---
---START---
INSERT INTO gtest23p VALUES (1), (2), (3);
---END---
---START---
CREATE TABLE gtest23q (a int PRIMARY KEY, b int REFERENCES gtest23p (y));
---END---
---START---
INSERT INTO gtest23q VALUES (1, 2);
---END---
---START---
-- ok
INSERT INTO gtest23q VALUES (2, 5);
---END---
---START---
-- error

-- domains
CREATE DOMAIN gtestdomain1 AS int CHECK (VALUE < 10);
---END---
---START---
CREATE TABLE gtest24 (a int PRIMARY KEY, b gtestdomain1 GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
INSERT INTO gtest24 (a) VALUES (4);
---END---
---START---
-- ok
INSERT INTO gtest24 (a) VALUES (6);
---END---
---START---
-- error

-- typed tables (currently not supported)
CREATE TYPE gtest_type AS (f1 integer, f2 text, f3 bigint);
---END---
---START---
CREATE TABLE gtest28 OF gtest_type (gemini_pk serial PRIMARY KEY, f1 WITH OPTIONS GENERATED ALWAYS AS (f2 * 2) STORED);
---END---
---START---
DROP TYPE gtest_type CASCADE;
---END---
---START---
CREATE TABLE gtest_parent (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint) PARTITION BY range (f1);
---END---
---START---
CREATE TABLE gtest_child PARTITION OF gtest_parent (
    f3 WITH OPTIONS GENERATED ALWAYS AS (f2 * 2) STORED
) FOR VALUES FROM ('2016-07-01') TO ('2016-08-01');
---END---
---START---
CREATE TABLE gtest_child (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint GENERATED ALWAYS AS (f2 * 2) STORED);
---END---
---START---
ALTER TABLE gtest_parent ATTACH PARTITION gtest_child FOR VALUES FROM ('2016-07-01') TO ('2016-08-01');
---END---
---START---
-- error
DROP TABLE gtest_parent, gtest_child;
---END---
---START---
CREATE TABLE gtest_parent (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint GENERATED ALWAYS AS (f2 * 2) STORED) PARTITION BY range (f1);
---END---
---START---
CREATE TABLE gtest_child PARTITION OF gtest_parent
  FOR VALUES FROM ('2016-07-01') TO ('2016-08-01');
---END---
---START---
-- inherits gen expr
CREATE TABLE gtest_child2 PARTITION OF gtest_parent (
    f3 WITH OPTIONS GENERATED ALWAYS AS (f2 * 22) STORED  -- overrides gen expr
) FOR VALUES FROM ('2016-08-01') TO ('2016-09-01');
---END---
---START---
CREATE TABLE gtest_child3 PARTITION OF gtest_parent (
    f3 DEFAULT 42  -- error
) FOR VALUES FROM ('2016-09-01') TO ('2016-10-01');
---END---
---START---
CREATE TABLE gtest_child3 PARTITION OF gtest_parent (
    f3 WITH OPTIONS GENERATED ALWAYS AS IDENTITY  -- error
) FOR VALUES FROM ('2016-09-01') TO ('2016-10-01');
---END---
---START---
CREATE TABLE gtest_child3 (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint);
---END---
---START---
ALTER TABLE gtest_parent ATTACH PARTITION gtest_child3 FOR VALUES FROM ('2016-09-01') TO ('2016-10-01');
---END---
---START---
-- error
DROP TABLE gtest_child3;
---END---
---START---
CREATE TABLE gtest_child3 (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint DEFAULT 42);
---END---
---START---
ALTER TABLE gtest_parent ATTACH PARTITION gtest_child3 FOR VALUES FROM ('2016-09-01') TO ('2016-10-01');
---END---
---START---
-- error
DROP TABLE gtest_child3;
---END---
---START---
CREATE TABLE gtest_child3 (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint GENERATED ALWAYS AS IDENTITY);
---END---
---START---
ALTER TABLE gtest_parent ATTACH PARTITION gtest_child3 FOR VALUES FROM ('2016-09-01') TO ('2016-10-01');
---END---
---START---
-- error
DROP TABLE gtest_child3;
---END---
---START---
CREATE TABLE gtest_child3 (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint GENERATED ALWAYS AS (f2 * 33) STORED);
---END---
---START---
ALTER TABLE gtest_parent ATTACH PARTITION gtest_child3 FOR VALUES FROM ('2016-09-01') TO ('2016-10-01');
---END---
---START---
\d gtest_child
\d gtest_child2
\d gtest_child3
INSERT INTO gtest_parent (f1, f2) VALUES ('2016-07-15', 1);
---END---
---START---
SELECT * FROM gtest_parent;
---END---
---START---
SELECT * FROM gtest_child;
---END---
---START---
UPDATE gtest_parent SET f1 = f1 + 60;
---END---
---START---
SELECT * FROM gtest_parent;
---END---
---START---
SELECT * FROM gtest_child3;
---END---
---START---
CREATE TABLE gtest_part_key (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint GENERATED ALWAYS AS (f2 * 2) STORED) PARTITION BY range (f3);
---END---
---START---
CREATE TABLE gtest_part_key (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 bigint, f3 bigint GENERATED ALWAYS AS (f2 * 2) STORED) PARTITION BY range ((f3 * 3));
---END---
---START---
-- ALTER TABLE ... ADD COLUMN
CREATE TABLE gtest25 (a int PRIMARY KEY);
---END---
---START---
INSERT INTO gtest25 VALUES (3), (4);
---END---
---START---
ALTER TABLE gtest25 ADD COLUMN b int GENERATED ALWAYS AS (a * 3) STORED;
---END---
---START---
SELECT * FROM gtest25 ORDER BY a;
---END---
---START---
ALTER TABLE gtest25 ADD COLUMN x int GENERATED ALWAYS AS (b * 4) STORED;
---END---
---START---
-- error
ALTER TABLE gtest25 ADD COLUMN x int GENERATED ALWAYS AS (z * 4) STORED;
---END---
---START---
-- error
ALTER TABLE gtest25 ADD COLUMN c int DEFAULT 42,
  ADD COLUMN x int GENERATED ALWAYS AS (c * 4) STORED;
---END---
---START---
ALTER TABLE gtest25 ADD COLUMN d int DEFAULT 101;
---END---
---START---
ALTER TABLE gtest25 ALTER COLUMN d SET DATA TYPE float8,
  ADD COLUMN y float8 GENERATED ALWAYS AS (d * 4) STORED;
---END---
---START---
SELECT * FROM gtest25 ORDER BY a;
---END---
---START---
\d gtest25

-- ALTER TABLE ... ALTER COLUMN
CREATE TABLE gtest27 (
    a int,
    b int,
    x int GENERATED ALWAYS AS ((a + b) * 2) STORED
);
---END---
---START---
INSERT INTO gtest27 (a, b) VALUES (3, 7), (4, 11);
---END---
---START---
ALTER TABLE gtest27 ALTER COLUMN a TYPE text;
---END---
---START---
-- error
ALTER TABLE gtest27 ALTER COLUMN x TYPE numeric;
---END---
---START---
\d gtest27
SELECT * FROM gtest27;
---END---
---START---
ALTER TABLE gtest27 ALTER COLUMN x TYPE boolean USING x <> 0;
---END---
---START---
-- error
ALTER TABLE gtest27 ALTER COLUMN x DROP DEFAULT;
---END---
---START---
-- error
-- It's possible to alter the column types this way:
ALTER TABLE gtest27
  DROP COLUMN x,
  ALTER COLUMN a TYPE bigint,
  ALTER COLUMN b TYPE bigint,
  ADD COLUMN x bigint GENERATED ALWAYS AS ((a + b) * 2) STORED;
---END---
---START---
\d gtest27
-- Ideally you could just do this, but not today (and should x change type?):
ALTER TABLE gtest27
  ALTER COLUMN a TYPE float8,
  ALTER COLUMN b TYPE float8;
---END---
---START---
-- error
\d gtest27
SELECT * FROM gtest27;
---END---
---START---
CREATE TABLE gtest29 (gemini_pk serial PRIMARY KEY, a integer, b integer GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
INSERT INTO gtest29 (a) VALUES (3), (4);
---END---
---START---
ALTER TABLE gtest29 ALTER COLUMN a DROP EXPRESSION;
---END---
---START---
-- error
ALTER TABLE gtest29 ALTER COLUMN a DROP EXPRESSION IF EXISTS;
---END---
---START---
-- notice
ALTER TABLE gtest29 ALTER COLUMN b DROP EXPRESSION;
---END---
---START---
INSERT INTO gtest29 (a) VALUES (5);
---END---
---START---
INSERT INTO gtest29 (a, b) VALUES (6, 66);
---END---
---START---
SELECT * FROM gtest29;
---END---
---START---
\d gtest29

-- check that dependencies between columns have also been removed
ALTER TABLE gtest29 DROP COLUMN a;
---END---
---START---
-- should not drop b
\d gtest29

-- with inheritance
CREATE TABLE gtest30 (
    a int,
    b int GENERATED ALWAYS AS (a * 2) STORED
);
---END---
---START---
CREATE TABLE gtest30_1 (gemini_pk serial PRIMARY KEY) INHERITS (gtest30);
---END---
---START---
ALTER TABLE gtest30 ALTER COLUMN b DROP EXPRESSION;
---END---
---START---
\d gtest30
\d gtest30_1
DROP TABLE gtest30 CASCADE;
---END---
---START---
CREATE TABLE gtest30 (gemini_pk serial PRIMARY KEY, a integer, b integer GENERATED ALWAYS AS (a * 2) STORED);
---END---
---START---
CREATE TABLE gtest30_1 (gemini_pk serial PRIMARY KEY) INHERITS (gtest30);
---END---
---START---
ALTER TABLE ONLY gtest30 ALTER COLUMN b DROP EXPRESSION;
---END---
---START---
-- error
\d gtest30
\d gtest30_1
ALTER TABLE gtest30_1 ALTER COLUMN b DROP EXPRESSION;
---END---
---START---
-- error

-- triggers
CREATE TABLE gtest26 (
    a int PRIMARY KEY,
    b int GENERATED ALWAYS AS (a * 2) STORED
);
---END---
---START---
CREATE FUNCTION gtest_trigger_func() RETURNS trigger
  LANGUAGE plpgsql
AS $$
BEGIN
  IF tg_op IN ('DELETE', 'UPDATE') THEN
    RAISE INFO '%: %: old = %', TG_NAME, TG_WHEN, OLD;
  END IF;
  IF tg_op IN ('INSERT', 'UPDATE') THEN
    RAISE INFO '%: %: new = %', TG_NAME, TG_WHEN, NEW;
  END IF;
  IF tg_op = 'DELETE' THEN
    RETURN OLD;
  ELSE
    RETURN NEW;
  END IF;
END
$$;
---END---
---START---
CREATE TRIGGER gtest1 BEFORE DELETE OR UPDATE ON gtest26
  FOR EACH ROW
  WHEN (OLD.b < 0)  -- ok
  EXECUTE PROCEDURE gtest_trigger_func();
---END---
---START---
CREATE TRIGGER gtest2a BEFORE INSERT OR UPDATE ON gtest26
  FOR EACH ROW
  WHEN (NEW.b < 0)  -- error
  EXECUTE PROCEDURE gtest_trigger_func();
---END---
---START---
CREATE TRIGGER gtest2b BEFORE INSERT OR UPDATE ON gtest26
  FOR EACH ROW
  WHEN (NEW.* IS NOT NULL)  -- error
  EXECUTE PROCEDURE gtest_trigger_func();
---END---
---START---
CREATE TRIGGER gtest2 BEFORE INSERT ON gtest26
  FOR EACH ROW
  WHEN (NEW.a < 0)
  EXECUTE PROCEDURE gtest_trigger_func();
---END---
---START---
CREATE TRIGGER gtest3 AFTER DELETE OR UPDATE ON gtest26
  FOR EACH ROW
  WHEN (OLD.b < 0)  -- ok
  EXECUTE PROCEDURE gtest_trigger_func();
---END---
---START---
CREATE TRIGGER gtest4 AFTER INSERT OR UPDATE ON gtest26
  FOR EACH ROW
  WHEN (NEW.b < 0)  -- ok
  EXECUTE PROCEDURE gtest_trigger_func();
---END---
---START---
INSERT INTO gtest26 (a) VALUES (-2), (0), (3);
---END---
---START---
SELECT * FROM gtest26 ORDER BY a;
---END---
---START---
UPDATE gtest26 SET a = a * -2;
---END---
---START---
SELECT * FROM gtest26 ORDER BY a;
---END---
---START---
DELETE FROM gtest26 WHERE a = -6;
---END---
---START---
SELECT * FROM gtest26 ORDER BY a;
---END---
---START---
DROP TRIGGER gtest1 ON gtest26;
---END---
---START---
DROP TRIGGER gtest2 ON gtest26;
---END---
---START---
DROP TRIGGER gtest3 ON gtest26;
---END---
---START---
-- Check that an UPDATE of "a" fires the trigger for UPDATE OF b, per
-- SQL standard.
CREATE FUNCTION gtest_trigger_func3() RETURNS trigger
  LANGUAGE plpgsql
AS $$
BEGIN
  RAISE NOTICE 'OK';
  RETURN NEW;
END
$$;
---END---
---START---
CREATE TRIGGER gtest11 BEFORE UPDATE OF b ON gtest26
  FOR EACH ROW
  EXECUTE PROCEDURE gtest_trigger_func3();
---END---
---START---
UPDATE gtest26 SET a = 1 WHERE a = 0;
---END---
---START---
DROP TRIGGER gtest11 ON gtest26;
---END---
---START---
TRUNCATE gtest26;
---END---
---START---
-- check that modifications of stored generated columns in triggers do
-- not get propagated
CREATE FUNCTION gtest_trigger_func4() RETURNS trigger
  LANGUAGE plpgsql
AS $$
BEGIN
  NEW.a = 10;
  NEW.b = 300;
  RETURN NEW;
END;
$$;
---END---
---START---
CREATE TRIGGER gtest12_01 BEFORE UPDATE ON gtest26
  FOR EACH ROW
  EXECUTE PROCEDURE gtest_trigger_func();
---END---
---START---
CREATE TRIGGER gtest12_02 BEFORE UPDATE ON gtest26
  FOR EACH ROW
  EXECUTE PROCEDURE gtest_trigger_func4();
---END---
---START---
CREATE TRIGGER gtest12_03 BEFORE UPDATE ON gtest26
  FOR EACH ROW
  EXECUTE PROCEDURE gtest_trigger_func();
---END---
---START---
INSERT INTO gtest26 (a) VALUES (1);
---END---
---START---
UPDATE gtest26 SET a = 11 WHERE a = 1;
---END---
---START---
SELECT * FROM gtest26 ORDER BY a;
---END---
---START---
CREATE TABLE gtest28a (gemini_pk serial PRIMARY KEY, a integer, b integer, c integer, x integer GENERATED ALWAYS AS (b * 2) STORED);
---END---
---START---
ALTER TABLE gtest28a DROP COLUMN a;
---END---
---START---
CREATE TABLE gtest28b (gemini_pk serial PRIMARY KEY, LIKE gtest28a INCLUDING GENERATED);
---END---
