---START---
-- sanity check of system catalog
SELECT attrelid, attname, attidentity FROM pg_attribute WHERE attidentity NOT IN ('', 'a', 'd');
---END---
---START---
CREATE TABLE itest1 (gemini_pk serial PRIMARY KEY, a integer GENERATED BY DEFAULT AS IDENTITY, b text);
---END---
---START---
CREATE TABLE itest2 (gemini_pk serial PRIMARY KEY, a bigint GENERATED ALWAYS AS IDENTITY, b text);
---END---
---START---
CREATE TABLE itest3 (gemini_pk serial PRIMARY KEY, a smallint GENERATED BY DEFAULT AS IDENTITY(START WITH 7 INCREMENT BY 5), b text);
---END---
---START---
ALTER TABLE itest3 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
-- error

SELECT table_name, column_name, column_default, is_nullable, is_identity, identity_generation, identity_start, identity_increment, identity_maximum, identity_minimum, identity_cycle FROM information_schema.columns WHERE table_name LIKE 'itest_' ORDER BY 1, 2;
---END---
---START---
-- internal sequences should not be shown here
SELECT sequence_name FROM information_schema.sequences WHERE sequence_name LIKE 'itest%';
---END---
---START---
SELECT pg_get_serial_sequence('itest1', 'a');
---END---
---START---
\d itest1_a_seq

CREATE TABLE itest4 (a int, b text);
---END---
---START---
ALTER TABLE itest4 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
-- error, requires NOT NULL
ALTER TABLE itest4 ALTER COLUMN a SET NOT NULL;
---END---
---START---
ALTER TABLE itest4 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
-- ok
ALTER TABLE itest4 ALTER COLUMN a DROP NOT NULL;
---END---
---START---
-- error, disallowed
ALTER TABLE itest4 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
-- error, already set
ALTER TABLE itest4 ALTER COLUMN b ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
-- error, wrong data type

-- for later
ALTER TABLE itest4 ALTER COLUMN b SET DEFAULT '';
---END---
---START---
-- @hengfeng: this crashes the emulator
-- CREATE TABLE itest_err_1 (gemini_pk serial PRIMARY KEY, a text GENERATED BY DEFAULT AS IDENTITY);
---END---
---START---
CREATE TABLE itest_err_2 (gemini_pk serial PRIMARY KEY, a integer GENERATED ALWAYS AS IDENTITY GENERATED BY DEFAULT AS IDENTITY);
---END---
---START---
CREATE TABLE itest_err_3 (gemini_pk serial PRIMARY KEY, a integer DEFAULT 5 GENERATED BY DEFAULT AS IDENTITY);
---END---
---START---
CREATE TABLE itest_err_4 (gemini_pk serial PRIMARY KEY, a serial GENERATED BY DEFAULT AS IDENTITY);
---END---
---START---
INSERT INTO itest1 DEFAULT VALUES;
---END---
---START---
INSERT INTO itest1 DEFAULT VALUES;
---END---
---START---
INSERT INTO itest2 DEFAULT VALUES;
---END---
---START---
INSERT INTO itest2 DEFAULT VALUES;
---END---
---START---
INSERT INTO itest3 DEFAULT VALUES;
---END---
---START---
INSERT INTO itest3 DEFAULT VALUES;
---END---
---START---
INSERT INTO itest4 DEFAULT VALUES;
---END---
---START---
INSERT INTO itest4 DEFAULT VALUES;
---END---
---START---
SELECT * FROM itest1;
---END---
---START---
SELECT * FROM itest2;
---END---
---START---
SELECT * FROM itest3;
---END---
---START---
SELECT * FROM itest4;
---END---
---START---
CREATE TABLE itest5 (gemini_pk serial PRIMARY KEY, a integer GENERATED ALWAYS AS IDENTITY, b text);
---END---
---START---
INSERT INTO itest5 VALUES (1, 'a');
---END---
---START---
-- error
INSERT INTO itest5 VALUES (DEFAULT, 'a');
---END---
---START---
-- ok
INSERT INTO itest5 VALUES (2, 'b'), (3, 'c');
---END---
---START---
-- error
INSERT INTO itest5 VALUES (DEFAULT, 'b'), (3, 'c');
---END---
---START---
-- error
INSERT INTO itest5 VALUES (2, 'b'), (DEFAULT, 'c');
---END---
---START---
-- error
INSERT INTO itest5 VALUES (DEFAULT, 'b'), (DEFAULT, 'c');
---END---
---START---
-- ok

INSERT INTO itest5 OVERRIDING SYSTEM VALUE VALUES (-1, 'aa');
---END---
---START---
INSERT INTO itest5 OVERRIDING SYSTEM VALUE VALUES (-2, 'bb'), (-3, 'cc');
---END---
---START---
INSERT INTO itest5 OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 'dd'), (-4, 'ee');
---END---
---START---
INSERT INTO itest5 OVERRIDING SYSTEM VALUE VALUES (-5, 'ff'), (DEFAULT, 'gg');
---END---
---START---
INSERT INTO itest5 OVERRIDING SYSTEM VALUE VALUES (DEFAULT, 'hh'), (DEFAULT, 'ii');
---END---
---START---
INSERT INTO itest5 OVERRIDING USER VALUE VALUES (-1, 'aaa');
---END---
---START---
INSERT INTO itest5 OVERRIDING USER VALUE VALUES (-2, 'bbb'), (-3, 'ccc');
---END---
---START---
INSERT INTO itest5 OVERRIDING USER VALUE VALUES (DEFAULT, 'ddd'), (-4, 'eee');
---END---
---START---
INSERT INTO itest5 OVERRIDING USER VALUE VALUES (-5, 'fff'), (DEFAULT, 'ggg');
---END---
---START---
INSERT INTO itest5 OVERRIDING USER VALUE VALUES (DEFAULT, 'hhh'), (DEFAULT, 'iii');
---END---
---START---
SELECT * FROM itest5;
---END---
---START---
DROP TABLE itest5;
---END---
---START---
INSERT INTO itest3 VALUES (DEFAULT, 'a');
---END---
---START---
INSERT INTO itest3 VALUES (DEFAULT, 'b'), (DEFAULT, 'c');
---END---
---START---
SELECT * FROM itest3;
---END---
---START---
-- OVERRIDING tests

-- GENERATED BY DEFAULT

-- This inserts the row as presented:
INSERT INTO itest1 VALUES (10, 'xyz');
---END---
---START---
-- With GENERATED BY DEFAULT, OVERRIDING SYSTEM VALUE is not allowed
-- by the standard, but we allow it as a no-op, since it is of use if
-- there are multiple identity columns in a table, which is also an
-- extension.
INSERT INTO itest1 OVERRIDING SYSTEM VALUE VALUES (20, 'xyz');
---END---
---START---
-- This ignores the 30 and uses the sequence value instead:
INSERT INTO itest1 OVERRIDING USER VALUE VALUES (30, 'xyz');
---END---
---START---
SELECT * FROM itest1;
---END---
---START---
-- GENERATED ALWAYS

-- This is an error:
INSERT INTO itest2 VALUES (10, 'xyz');
---END---
---START---
-- This inserts the row as presented:
INSERT INTO itest2 OVERRIDING SYSTEM VALUE VALUES (20, 'xyz');
---END---
---START---
-- This ignores the 30 and uses the sequence value instead:
INSERT INTO itest2 OVERRIDING USER VALUE VALUES (30, 'xyz');
---END---
---START---
SELECT * FROM itest2;
---END---
---START---
-- UPDATE tests

-- GENERATED BY DEFAULT is not restricted.
UPDATE itest1 SET a = 101 WHERE a = 1;
---END---
---START---
UPDATE itest1 SET a = DEFAULT WHERE a = 2;
---END---
---START---
SELECT * FROM itest1;
---END---
---START---
-- GENERATED ALWAYS allows only DEFAULT.
UPDATE itest2 SET a = 101 WHERE a = 1;
---END---
---START---
-- error
UPDATE itest2 SET a = DEFAULT WHERE a = 2;
---END---
---START---
-- ok
SELECT * FROM itest2;
---END---
---START---
COPY tests

CREATE TABLE itest9 (a int GENERATED ALWAYS AS IDENTITY, b text, c bigint);

COPY itest9 FROM stdin;
100	foo	200
101	bar	201
\.
---END---
---START---
COPY itest9 (b, c) FROM stdin;
foo2	202
bar2	203
\.
---END---
---START---
SELECT * FROM itest9 ORDER BY c;
---END---
---START---
-- DROP IDENTITY tests

ALTER TABLE itest4 ALTER COLUMN a DROP IDENTITY;
---END---
---START---
ALTER TABLE itest4 ALTER COLUMN a DROP IDENTITY;
---END---
---START---
-- error
ALTER TABLE itest4 ALTER COLUMN a DROP IDENTITY IF EXISTS;
---END---
---START---
-- noop

INSERT INTO itest4 DEFAULT VALUES;
---END---
---START---
-- fails because NOT NULL is not dropped
ALTER TABLE itest4 ALTER COLUMN a DROP NOT NULL;
---END---
---START---
INSERT INTO itest4 DEFAULT VALUES;
---END---
---START---
SELECT * FROM itest4;
---END---
---START---
-- check that sequence is removed
SELECT sequence_name FROM itest4_a_seq;
---END---
---START---
CREATE TABLE itest10 (gemini_pk serial PRIMARY KEY, a integer GENERATED BY DEFAULT AS IDENTITY, b text);
---END---
---START---
CREATE TABLE itest11 (gemini_pk serial PRIMARY KEY, a integer GENERATED ALWAYS AS IDENTITY, b text);
---END---
---START---
CREATE VIEW itestv10 AS SELECT * FROM itest10;
---END---
---START---
CREATE VIEW itestv11 AS SELECT * FROM itest11;
---END---
---START---
INSERT INTO itestv10 DEFAULT VALUES;
---END---
---START---
INSERT INTO itestv10 DEFAULT VALUES;
---END---
---START---
INSERT INTO itestv11 DEFAULT VALUES;
---END---
---START---
INSERT INTO itestv11 DEFAULT VALUES;
---END---
---START---
SELECT * FROM itestv10;
---END---
---START---
SELECT * FROM itestv11;
---END---
---START---
INSERT INTO itestv10 VALUES (10, 'xyz');
---END---
---START---
INSERT INTO itestv10 OVERRIDING USER VALUE VALUES (11, 'xyz');
---END---
---START---
SELECT * FROM itestv10;
---END---
---START---
INSERT INTO itestv11 VALUES (10, 'xyz');
---END---
---START---
INSERT INTO itestv11 OVERRIDING SYSTEM VALUE VALUES (11, 'xyz');
---END---
---START---
SELECT * FROM itestv11;
---END---
---START---
DROP VIEW itestv10, itestv11;
---END---
---START---
CREATE TABLE itest13 (gemini_pk serial PRIMARY KEY, a integer);
---END---
---START---
-- add column to empty table
ALTER TABLE itest13 ADD COLUMN b int GENERATED BY DEFAULT AS IDENTITY;
---END---
---START---
INSERT INTO itest13 VALUES (1), (2), (3);
---END---
---START---
-- add column to populated table
ALTER TABLE itest13 ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY;
---END---
---START---
SELECT * FROM itest13;
---END---
---START---
-- various ALTER COLUMN tests

-- fail, not allowed for identity columns
ALTER TABLE itest1 ALTER COLUMN a SET DEFAULT 1;
---END---
---START---
CREATE TABLE itest5 (gemini_pk serial PRIMARY KEY, a serial, b text);
---END---
---START---
ALTER TABLE itest5 ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
ALTER TABLE itest3 ALTER COLUMN a TYPE int;
---END---
---START---
SELECT seqtypid::regtype FROM pg_sequence WHERE seqrelid = 'itest3_a_seq'::regclass;
---END---
---START---
\d itest3

ALTER TABLE itest3 ALTER COLUMN a TYPE text;
---END---
---START---
-- error

-- kinda silly to change property in the same command, but it should work
ALTER TABLE itest3
  ADD COLUMN c int GENERATED BY DEFAULT AS IDENTITY,
  ALTER COLUMN c SET GENERATED ALWAYS;
---END---
---START---
\d itest3


-- ALTER COLUMN ... SET

CREATE TABLE itest6 (a int GENERATED ALWAYS AS IDENTITY, b text);
---END---
---START---
INSERT INTO itest6 DEFAULT VALUES;
---END---
---START---
ALTER TABLE itest6 ALTER COLUMN a SET GENERATED BY DEFAULT SET INCREMENT BY 2 SET START WITH 100 RESTART;
---END---
---START---
INSERT INTO itest6 DEFAULT VALUES;
---END---
---START---
INSERT INTO itest6 DEFAULT VALUES;
---END---
---START---
SELECT * FROM itest6;
---END---
---START---
SELECT table_name, column_name, is_identity, identity_generation FROM information_schema.columns WHERE table_name = 'itest6' ORDER BY 1, 2;
---END---
---START---
ALTER TABLE itest6 ALTER COLUMN b SET INCREMENT BY 2;
---END---
---START---
-- fail, not identity


-- prohibited direct modification of sequence

ALTER SEQUENCE itest6_a_seq OWNED BY NONE;
---END---
---START---
CREATE TABLE itest7 (gemini_pk serial PRIMARY KEY, a integer GENERATED ALWAYS AS IDENTITY);
---END---
---START---
INSERT INTO itest7 DEFAULT VALUES;
---END---
---START---
SELECT * FROM itest7;
---END---
---START---
CREATE TABLE itest7a (gemini_pk serial PRIMARY KEY, b text) INHERITS (itest7);
---END---
---START---
CREATE TABLE itest7b (gemini_pk serial PRIMARY KEY, a integer);
---END---
---START---
CREATE TABLE itest7c (gemini_pk serial PRIMARY KEY, a integer GENERATED ALWAYS AS IDENTITY) INHERITS (itest7b);
---END---
---START---
INSERT INTO itest7c DEFAULT VALUES;
---END---
---START---
SELECT * FROM itest7c;
---END---
---START---
CREATE TABLE itest7d (gemini_pk serial PRIMARY KEY, a integer NOT NULL);
---END---
---START---
CREATE TABLE itest7e (gemini_pk serial PRIMARY KEY) INHERITS (itest7d);
---END---
---START---
ALTER TABLE itest7d ALTER COLUMN a ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
ALTER TABLE itest7d ADD COLUMN b int GENERATED ALWAYS AS IDENTITY;
---END---
---START---
-- error

SELECT table_name, column_name, is_nullable, is_identity, identity_generation FROM information_schema.columns WHERE table_name LIKE 'itest7%' ORDER BY 1, 2;
---END---
---START---
-- These ALTER TABLE variants will not recurse.
ALTER TABLE itest7 ALTER COLUMN a SET GENERATED BY DEFAULT;
---END---
---START---
ALTER TABLE itest7 ALTER COLUMN a RESTART;
---END---
---START---
ALTER TABLE itest7 ALTER COLUMN a DROP IDENTITY;
---END---
---START---
-- privileges
CREATE USER regress_identity_user1;
---END---
---START---
CREATE TABLE itest8 (gemini_pk serial PRIMARY KEY, a integer GENERATED ALWAYS AS IDENTITY, b text);
---END---
---START---
GRANT SELECT, INSERT ON itest8 TO regress_identity_user1;
---END---
---START---
SET ROLE regress_identity_user1;
---END---
---START---
INSERT INTO itest8 DEFAULT VALUES;
---END---
---START---
SELECT * FROM itest8;
---END---
---START---
RESET ROLE;
---END---
---START---
DROP TABLE itest8;
---END---
---START---
DROP USER regress_identity_user1;
---END---
---START---
CREATE TABLE itest8 (gemini_pk serial PRIMARY KEY, f1 integer);
---END---
---START---
ALTER TABLE itest8
  ADD COLUMN f2 int NOT NULL,
  ALTER COLUMN f2 ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
ALTER TABLE itest8
  ADD COLUMN f3 int NOT NULL,
  ALTER COLUMN f3 ADD GENERATED ALWAYS AS IDENTITY,
  ALTER COLUMN f3 SET GENERATED BY DEFAULT SET INCREMENT 10;
---END---
---START---
ALTER TABLE itest8
  ADD COLUMN f4 int;
---END---
---START---
ALTER TABLE itest8
  ALTER COLUMN f4 SET NOT NULL,
  ALTER COLUMN f4 ADD GENERATED ALWAYS AS IDENTITY,
  ALTER COLUMN f4 SET DATA TYPE bigint;
---END---
---START---
ALTER TABLE itest8
  ADD COLUMN f5 int GENERATED ALWAYS AS IDENTITY;
---END---
---START---
ALTER TABLE itest8
  ALTER COLUMN f5 DROP IDENTITY,
  ALTER COLUMN f5 DROP NOT NULL,
  ALTER COLUMN f5 SET DATA TYPE bigint;
---END---
---START---
INSERT INTO itest8 VALUES(0), (1);
---END---
---START---
-- This does not work when the table isn't empty.  That's intentional,
-- since ADD GENERATED should only affect later insertions:
ALTER TABLE itest8
  ADD COLUMN f22 int NOT NULL,
  ALTER COLUMN f22 ADD GENERATED ALWAYS AS IDENTITY;
---END---
---START---
TABLE itest8;
---END---
---START---
\d+ itest8
\d itest8_f2_seq
\d itest8_f3_seq
\d itest8_f4_seq
\d itest8_f5_seq
DROP TABLE itest8;
---END---
---START---
-- typed tables (currently not supported)

CREATE TYPE itest_type AS (f1 integer, f2 text, f3 bigint);
---END---
---START---
CREATE TABLE itest12 OF itest_type (gemini_pk serial PRIMARY KEY, f1 WITH OPTIONS GENERATED ALWAYS AS IDENTITY);
---END---
---START---
-- error
DROP TYPE itest_type CASCADE;
---END---
---START---
CREATE TABLE itest_parent (gemini_pk serial PRIMARY KEY, f1 date NOT NULL, f2 text, f3 bigint) PARTITION BY range (f1);
---END---
---START---
CREATE TABLE itest_child PARTITION OF itest_parent (
    f3 WITH OPTIONS GENERATED ALWAYS AS IDENTITY
) FOR VALUES FROM ('2016-07-01') TO ('2016-08-01');
---END---
---START---
-- error
DROP TABLE itest_parent;
---END---
---START---
CREATE TABLE itest14 (gemini_pk serial PRIMARY KEY, id serial);
---END---
---START---
ALTER TABLE itest14 ALTER id DROP DEFAULT;
---END---
---START---
ALTER TABLE itest14 ALTER id ADD GENERATED BY DEFAULT AS IDENTITY;
---END---
---START---
INSERT INTO itest14 (id) VALUES (DEFAULT);
---END---
---START---
CREATE TABLE itest15 (gemini_pk serial PRIMARY KEY, id integer GENERATED ALWAYS AS IDENTITY NULL);
---END---
---START---
CREATE TABLE itest15 (gemini_pk serial PRIMARY KEY, id integer NULL GENERATED ALWAYS AS IDENTITY);
---END---
---START---
CREATE TABLE itest15 (gemini_pk serial PRIMARY KEY, id integer GENERATED ALWAYS AS IDENTITY NOT NULL);
---END---
---START---
DROP TABLE itest15;
---END---
---START---
CREATE TABLE itest15 (gemini_pk serial PRIMARY KEY, id integer NOT NULL GENERATED ALWAYS AS IDENTITY);
---END---
---START---
DROP TABLE itest15;
---END---
---START---
CREATE TABLE itest15 (gemini_pk serial PRIMARY KEY, a integer GENERATED ALWAYS AS IDENTITY, b text);
---END---
---START---
CREATE TABLE itest16 (gemini_pk serial PRIMARY KEY, a integer GENERATED BY DEFAULT AS IDENTITY, b text);
---END---
---START---
MERGE INTO itest15 t
USING (SELECT 10 AS s_a, 'inserted by merge' AS s_b) s
ON t.a = s.s_a
WHEN NOT MATCHED THEN
	INSERT (a, b) VALUES (s.s_a, s.s_b);
---END---
---START---
-- Used to fail, but now it works and ignores the user supplied value
MERGE INTO itest15 t
USING (SELECT 20 AS s_a, 'inserted by merge' AS s_b) s
ON t.a = s.s_a
WHEN NOT MATCHED THEN
	INSERT (a, b) OVERRIDING USER VALUE VALUES (s.s_a, s.s_b);
---END---
---START---
MERGE INTO itest15 t
USING (SELECT 30 AS s_a, 'inserted by merge' AS s_b) s
ON t.a = s.s_a
WHEN NOT MATCHED THEN
	INSERT (a, b) OVERRIDING SYSTEM VALUE VALUES (s.s_a, s.s_b);
---END---
---START---
MERGE INTO itest16 t
USING (SELECT 10 AS s_a, 'inserted by merge' AS s_b) s
ON t.a = s.s_a
WHEN NOT MATCHED THEN
	INSERT (a, b) VALUES (s.s_a, s.s_b);
---END---
---START---
MERGE INTO itest16 t
USING (SELECT 20 AS s_a, 'inserted by merge' AS s_b) s
ON t.a = s.s_a
WHEN NOT MATCHED THEN
	INSERT (a, b) OVERRIDING USER VALUE VALUES (s.s_a, s.s_b);
---END---
---START---
MERGE INTO itest16 t
USING (SELECT 30 AS s_a, 'inserted by merge' AS s_b) s
ON t.a = s.s_a
WHEN NOT MATCHED THEN
	INSERT (a, b) OVERRIDING SYSTEM VALUE VALUES (s.s_a, s.s_b);
---END---
---START---
SELECT * FROM itest15;
---END---
---START---
SELECT * FROM itest16;
---END---
---START---
DROP TABLE itest15;
---END---
---START---
DROP TABLE itest16;
---END---
